### ISSUE TITLE
where to fine the "shapefiles_folder/IUs_9May2024.shp" file?

### ISSUE THREAD

**Issue by liamxg** [saloni-nd/scientific-discovery#3]
Dear @saloni-nd,

Could I know where to find "shapefiles_folder/IUs_9May2024.shp" file, thanks.

Best,
Liam

**Comment by saloni-nd** [comment]
Hi @liamxg, sorry I missed this! You can find the shape files on Google Drive.

I've added more details on how to recreate the chart in the README file here: https://github.com/owid/notebooks/tree/main/SaloniDattani/Trachoma

**Comment by liamxg** [comment]
Dear @saloni-nd ,

Thanks for your help.

Best,
Liam
